<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>01. 封装Promise,如果有请求错误, 依然能返回那些请求对的值</title>
</head>
<body>

</body>
<script>
    const getData = (url) => new Promise((resolve, reject) => {
        fetch(url).then((response) => {
            return response.json();
        })
        .then((data) => {
            resolve(data);
        })
        .catch(() => {
            resolve('error');
        });
    });
    const getDataList = (urlList) => {
        const promiseList = urlList.map((url) => getData(url));
        return Promise.all(promiseList).then((list) => {
            return list.map((v, i) => {
                if (v === 'error') {
                    return `第${i + 1}个请求失败`;
                }
                return v;
            });
        });
    };
    getDataList(['./data.json', './dat.json', './dat.json', 'https://mp.weixin.qq.com/s/L2D5xyu37rWtTWpkUaQa2w']).then(value => {
        console.log(value);
    });
</script>
</html>
